### ISSUE TITLE
Checkconn attempts IPV6 connections on a system with no IPV6

### ISSUE THREAD

**Issue by Elethiomel** [lwithers/checkconn#2]
If DNS entry has both an A record and an AAAA record, checkconn will attempt to use the AAAA record even on a system with no IPV6 stack. Changing this line - 

https://github.com/lwithers/checkconn/blob/b6e03ade17ae82b7293a4da717cad3102aaae79b/checkconn.go#L226

to "tcp4" forces an IPV4 connection which will work in this case, however, this prevents the checking of IPV6 connections.

Would it be possible to detect what IP versions are available on a system and limit checkconn to those addresses?

**Comment by lwithers** [comment]
I don't think this is easy to do, I'm afraid. It could have a `-4` command line flag though?

**Comment by lwithers** [comment]
There's a `-4` and a `-6` flag in v1.1.0.
